test:
  adapter: postgresql
  encoding: unicode
  database: pibble_gear_test
  pool: 5
  timeout: 5000

development:
  adapter: postgresql
  encoding: unicode
  database: pibble_gear_development
  pool: 5
  timeout: 5000


production:
  adapter: postgresql
  encoding: unicode
  database: pibble_gear_production
  pool: 5
  timeout: 5000

